- name: Build with Buildozer
        run: |
          # 1. Limpeza radical do ambiente
          rm -rf .buildozer
          
          # 2. Remover o Ant do sistema de forma permanente durante este job
          sudo rm -rf /home/runner/.buildozer/android/platform/apache-ant*
          
          # 3. Remover o Ant do PATH para garantir que o Buildozer não o localize
          export PATH=$(echo $PATH | sed -e 's|/home/runner/.buildozer/android/platform/apache-ant-1.9.4/bin:||g')
          
          # 4. Forçar o build usando Gradle
          buildozer -v android debug
